library(dplyr)
library(stringr)
library(purrr)
library(readr)
library(lubridate)

files <- list.files("data/downloads", full.names = TRUE)

# Officer count data is yearly so need to load it separately before joining it to the crime data
crime_files <- files[!grepl("_officers", files)]
officer_files <- files[grepl("_officers", files)]

crime_data <- tibble(series = c(), month = c(), arson = c(), assaults = c(), 
                     burglary = c(), gta = c(), homicides = c(), larceny = c(), ori = c())

# pull ORI and crime from file names generated by fbi_scraper.py
# expected format: data/downloads/ORI_crime.csv 
crime_data <- map_dfr(crime_files, function(file_path) {
  crime_type <- str_split(file_path, "[/._]")[[1]][4]
  ori <- str_split(file_path, "[/._]")[[1]][3]
  
  read.csv(file_path, colClasses = "character") |>   # force all as character
    slice(1) |> # drop second "clearances" row we don't care about
    pivot_longer(
      cols = starts_with("X"), 
      names_to = "month", 
      values_to = "count"
    ) |>
    mutate(
      count = ifelse(is.na(count), 0, as.integer(count)), # convert to integer values with NA values as 0s
      crime_type = crime_type,
      ori = ori,
      month = my(sub("^X", "", month)), # convert month string to Date object
      year = year(month)
    )
})

# pivot crimes to columns 
crime_data <- crime_data |>
  pivot_wider(
    names_from = crime_type,
    values_from = count,
    id_cols = c(series, month, ori, year)
  )

# read in officer data using the same formatting as the crime data
officer_counts <- tibble(ori = c(), year = c(), officers = c())
for(file_path in officer_files){
  temp_file <- read.csv(file_path)|>
    pivot_longer(cols = where(is.numeric)|where(is.logical), names_to = "year", values_to = "officers")|>
    mutate(ori =  str_split(file_path, "[/._]")[[1]][3])|>
    mutate(year = as.numeric(sub("^X", "", year)))|>
    mutate(officers = if_else(officers == 0, NA, officers))|>
    select(ori, year, officers)
  # add temp_file to total file
  officer_counts <- bind_rows(officer_counts, temp_file)
}

crime_data <- left_join(crime_data, officer_counts, by = join_by(ori, year))

saveRDS(crime_data, "data/crime_data.rds")