<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>main_econometrics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="main_econometrics_files/libs/clipboard/clipboard.min.js"></script>
<script src="main_econometrics_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="main_econometrics_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="main_econometrics_files/libs/quarto-html/popper.min.js"></script>
<script src="main_econometrics_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="main_econometrics_files/libs/quarto-html/anchor.min.js"></script>
<link href="main_econometrics_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="main_econometrics_files/libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="main_econometrics_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="main_econometrics_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="main_econometrics_files/libs/bootstrap/bootstrap-94545e8bded4fee647f2f9452f0eb602.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="main_econometrics_files/libs/kePrint-0.0.1/kePrint.js"></script>

<link href="main_econometrics_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">



</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">




<!--
# PAPER TODOs
# ensure modeling interpretation is correct 
-->
<div style="text-align: center; font-size: 21pt;">
<p><strong>Minnesota Crime: Patterns Over Time and Across COVID</strong></p>
<p>A Capstone Project for the Department of Math &amp; Statistics</p>
<p>William Hamilton Borer Seabloom</p>
<p>Advised by Dr.&nbsp;Tyler George</p>
<p>Cornell College</p>
<p>Feb x 2026</p>
</div>
<section id="abstract" class="level3">
<h3 class="anchored" data-anchor-id="abstract">Abstract</h3>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; In this paper, a 1998 study examining the sociological factors that impact crime across Minnesota counties is revisited. The original study’s parameters and data are extended from 1998 to the present and analyzed across two five-year periods before and after the COVID-19 pandemic. A clear spike in crime during COVID has been noted in previous literature, and this study examines whether traditional sociological predictors of crime changed both during COVID and over the longer period from 1998 to the present. The analysis employs the same core techniques used in the original study, including correlation analysis and OLS regression, with additional LASSO regression and structural break tests, to assess how the relationships between crime and its determinants evolved over time.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Consistent with previous literature, a clear increase in crime during the COVID period is initially observed. Additionally, graphical analysis reveals several significant correlations between classic predictors and crime, as well as apparent shifts in these relationships during COVID. However, once these relationships are formally modeled using OLS regression, the interaction terms and direct effects associated with COVID become statistically insignificant, leaving only a small subset of the original predictors with meaningful explanatory power. While these remaining variables reflect some changes from the original 1998 study, they also indicate continuity in key determinants of crime. Notably, the inclusion of an indicator variable for counties containing tribal reservations emerges as a meaningful addition, with both its main effect and its interaction with net migration showing statistical significance. Median household income and population density also remain significant predictors of crime. Overall, these findings suggest that while crime levels increased during the COVID period, the underlying sociological relationships driving crime across Minnesota counties remained largely stable. At the same time, the results highlight an evolution in the importance of certain predictors since the 1998 study, particularly the role of reservations and migration, which expand upon the original findings regarding the factors influencing county-level crime.<br>
</p>
</section>
<section id="introduction" class="level3">
<h3 class="anchored" data-anchor-id="introduction">Introduction</h3>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; In 1998 J. Mark Norman and Donald E. Arwood [1] published a paper titled “A Social Disorganization Theory of County Crime Rates in Minnesota” describing how the many different sociological measures of a society’s organization and control affect the crime rates in a community. These factors were measured across Minnesota counties and included factors such as education, wages, population density, and police presence. Recently, beginning during early 2020, the COVID-19 pandemic changed many factors of our society and disrupted many dimensions of social life. As discussed by Boman and Gallupe in 2020 [3] one of these many impacts was on crime rates, particularly in relation to the more serious violent crimes analyzed in Norman and Arwood’s 1998 study [1]. This raises an important question: Across Minnesota counties, how have the relationships between crime and its determinants changed over time, particularly in response to the COVID-19 pandemic?<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The main goal of this research is to build on Norman and Arwood’s 1998 study, by not only redoing the analysis with recent data but also looking at how these relationships have changed due to the COVID-19 pandemic. With crime and its prevention being such a large part of our world, and COVID changing many key parts of our society, it is important to reevaluate how typical sociological factors believed to relate to crime could have shifted during the COVID-19 pandemic. The state of these relationships today is also important in the future prediction/prevention of crime particularly for regulations on a county or state level.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; To investigate this question, the study will compare crime counts from the FBI’s Crime Data Explorer with demographic and socioeconomic indicators drawn from the U.S. Census five-year county-level estimates. The analysis will include all 87 Minnesota counties and will operationalize crime rates as the number of part I index offenses (homicide, burglary, robbery, aggravated assault, rape, larceny, motor vehicle theft, and arson) per county, normalized by population. This definition of crime aligns with Norman and Arwood’s earlier work [1] while also building on the more serious offenses that Boman and Gallupe (2020) [3] identified as trending upward during the COVID-19 pandemic. Differences in crime rates, averaged across the five-year periods before and after the onset of the pandemic, will be examined to assess whether structural changes occurred. These differences will be evaluated through statistical modeling of both the pre and post-pandemic county-level data, as well as models estimating changes over time.</p>
</section>
<section id="literature-review" class="level3">
<h3 class="anchored" data-anchor-id="literature-review">Literature Review</h3>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; This project is informed by several key sources: Norman and Arwood (1998) [1], James and Logan (2008) [2], and Boman and Gallupe (2020) [3]. Together, these works provide a foundation for understanding the sociological determinants of crime, the limitations of available data, and the unique disruptions brought about by the COVID-19 pandemic.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Norman and Arwood’s 1998 study analyzed the relationship between crime rates and a variety of sociological measures at the county level in Minnesota. Their findings demonstrated that among a variety of traditional sociological indicators of crime only alcohol consumption proxied by the county’s alcohol tax revenue, net migration in and out of the county, and households missing one or both parents, were significantly related to crime in Minnesota counties at the .05 level.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<caption>Variables in the Original Regression</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Variable</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">B</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">SE_B</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Beta</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">T</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Sig_T</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">ALCOHOLTAXES</td>
<td style="text-align: left;">1595.33990</td>
<td style="text-align: left;">380.76236</td>
<td style="text-align: left;">0.33367</td>
<td style="text-align: left;">4.19000</td>
<td style="text-align: left;">0.00010</td>
</tr>
<tr class="even">
<td style="text-align: left;">BELOWPOVERTYLINE</td>
<td style="text-align: left;">4.65875</td>
<td style="text-align: left;">2.74999</td>
<td style="text-align: left;">0.15941</td>
<td style="text-align: left;">1.69400</td>
<td style="text-align: left;">0.09430</td>
</tr>
<tr class="odd">
<td style="text-align: left;">COPRATIO</td>
<td style="text-align: left;">-1.72003</td>
<td style="text-align: left;">1.97365</td>
<td style="text-align: left;">-0.06510</td>
<td style="text-align: left;">-0.87100</td>
<td style="text-align: left;">0.38620</td>
</tr>
<tr class="even">
<td style="text-align: left;">PERSONSWITHDIPLOMA</td>
<td style="text-align: left;">3.78480</td>
<td style="text-align: left;">3.84462</td>
<td style="text-align: left;">0.11740</td>
<td style="text-align: left;">0.98400</td>
<td style="text-align: left;">0.32800</td>
</tr>
<tr class="odd">
<td style="text-align: left;">FEMALEHEADED</td>
<td style="text-align: left;">0.16999</td>
<td style="text-align: left;">0.43491</td>
<td style="text-align: left;">0.02303</td>
<td style="text-align: left;">0.39100</td>
<td style="text-align: left;">0.69700</td>
</tr>
<tr class="even">
<td style="text-align: left;">HETEROGENEITY</td>
<td style="text-align: left;">41.59058</td>
<td style="text-align: left;">25.20594</td>
<td style="text-align: left;">0.12895</td>
<td style="text-align: left;">1.65000</td>
<td style="text-align: left;">0.10310</td>
</tr>
<tr class="odd">
<td style="text-align: left;">NETMIGRATION</td>
<td style="text-align: left;">2.95424</td>
<td style="text-align: left;">1.08834</td>
<td style="text-align: left;">0.23224</td>
<td style="text-align: left;">2.71400</td>
<td style="text-align: left;">0.00820</td>
</tr>
<tr class="even">
<td style="text-align: left;">NOT2PARENTS</td>
<td style="text-align: left;">83.28531</td>
<td style="text-align: left;">23.98275</td>
<td style="text-align: left;">0.33217</td>
<td style="text-align: left;">3.47300</td>
<td style="text-align: left;">0.00090</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PERSONSPERMILE</td>
<td style="text-align: left;">139.62194</td>
<td style="text-align: left;">72.31688</td>
<td style="text-align: left;">0.16876</td>
<td style="text-align: left;">1.93100</td>
<td style="text-align: left;">0.05730</td>
</tr>
<tr class="even">
<td style="text-align: left;">PERCENTYOUNGMALES</td>
<td style="text-align: left;">-207.83213</td>
<td style="text-align: left;">193.87303</td>
<td style="text-align: left;">-0.08147</td>
<td style="text-align: left;">-1.07200</td>
<td style="text-align: left;">0.28710</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Constant</td>
<td style="text-align: left;">-977.27280</td>
<td style="text-align: left;">374.18150</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">-2.61200</td>
<td style="text-align: left;">0.01080</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; This work provides the methodological and theoretical foundation for the present project. While their study focused on the sociological context of the late 20th century, this research builds upon their approach by incorporating data up to the 2024 ACS 5 estimates and examining how these relationships may have shifted due to the COVID-19 pandemic.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; While this study aims to replicate the factors studied in Norman and Arwood’s original study there are some key differences in the analyses. Comparing the variables used in each study, both crime rates are a 5 year average of part 1 index crimes retrieved from the FBI’s crime reports. To measure household income levels the study includes the median income, percentage of the population below $5000 income, and below the poverty line. Both studies draw from the U.S census’ 5 year ACS estimates. The same is done for the measures of heterogeneity, net migration, households with less than two parents, the percent of the population made up of young males, and the percent of the population with a high school diploma or greater. In the original study, population density is stated to come from the census’ estimates, but due to lack of availability is determined in this study to be the population of the county divided by the area of the county in m<sup>2</sup>. The final explanatory variable used in their study, revenue from taxes on alcohol sales, comes from the Minnesota Department of Revenue website and is also averaged across 5 year periods. Having mostly the same source data as Norman and Arwood’s [1] original study, a general comparison to their original 1998 study is still possible with the understanding of the potential and real changes in the data’s collection and reporting.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; In order to track some of these changes, James and Logan’s 2008 report provides an overview of how the FBI collects and reports crime statistics, detailing the methodologies, limitations, and potential sources of bias within the Uniform Crime Reporting (UCR) database. Their report is particularly important because it highlights challenges such as underreporting, changes in reporting practices, and differences in local enforcement priorities. James and Logan state that underreporting in the FBI crime data is a large problem, with systematic errors produced from the way that the data is collected. This bias stems from the fact that the only crimes the FBI report are ones that the police have reported to them, and police officers are only aware of citizen reported crimes leading to two large sources of underreporting. Changes in reporting practices also affect this data, in particular the arson and rape counts. The way that rape was defined in this data changed in 2013 to remove the requirement of it being ‘forcible’ increasing the counts of this crime around this period as local law enforcement agencies changed their definition.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Furthermore, in any one instance of crimes being committed e.g a break in and homicide, only the homicide will be reported as it is the more severe of the two crimes. This leads to additional underreporting of less ‘severe’ crimes frequently committed in tandem with more ‘severe’ crimes. The one exception to this rule being arson which is counted on top of any crime it is committed with. However, arson counts are only recorded if it can be proven that the fire was willfully set meaning it is difficult to actually prove and then report arson as an offense.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; All of these insights are crucial for interpreting the results of this project, as they remind us that observed patterns in county-level crime rates may partly reflect variation in data quality or reporting practices rather than actual changes in criminal activity. By incorporating this perspective, this study can more carefully interpret both the limitations and strengths of using FBI crime statistics in the context of this paper’s results.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Boman and Gallupe’s research examines the effects of the COVID-19 pandemic on crime trends, with particular attention to how crime patterns shifted during periods of widespread social disruption. They found that while many types of crime declined during the pandemic, homicide and other serious violent crimes rose due to young people (primarily males) being put in positions where they were in close proximity to partners or family members and further from their friends. This change in social structures led to less time spent with friends in the situations where the smaller crimes such as vandalism are often committed. They also hypothesized that the higher counts of more severe crimes such as homicide and aggravated assault were the result of these potential minor offenders being moved into a situation where they have a much greater chance of committing a violent crime against their partners or family members due to a lack of normal outlets. Their findings suggest that structural shocks, such as a global pandemic, can have separate effects on different categories of crime. This study directly informs the paper, as it investigates whether similar shifts occurred in Minnesota counties, particularly in the increased prevalence of violent crime relative to overall crime rates as well as a potential shift in the predictability of crime after the pandemic.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Taken together, these works establish the intellectual groundwork for this project. Norman and Arwood demonstrate how sociological indicators can be systematically linked to crime rates at the county level. James and Logan’s 2008 report provides guidance on the interpretation of crime statistics, ensuring that my analysis acknowledges the methodological challenges of working with FBI data. Finally, Boman and Gallupe highlight the COVID-19 pandemic as a significant structural event that reshaped crime in the United States, motivating the inclusion of a temporal comparison between pre and post-pandemic trends in Minnesota. Building on these sources, my study aims to contribute by both replicating and extending prior methods to assess whether longstanding sociological-crime relationships have been altered by the COVID-19 pandemic.</p>
</section>
<section id="hypotheses" class="level3">
<h3 class="anchored" data-anchor-id="hypotheses">Hypotheses</h3>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Consistent with the findings of Norman and Arwood [1], we would expect that prior to the COVID-19 pandemic, county-level crime rates will be positively associated with indicators of social disorganization, particularly higher net migration rates, greater proportions of households missing one or both parents, and higher levels of alcohol consumption proxied by county alcohol tax revenue. In contrast, more traditional socioeconomic indicators such as median household income, educational attainment, and population density are expected to exhibit weak or statistically insignificant relationships with crime in the pre-pandemic period, as is found in earlier work.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The central hypothesis of this study is that COVID represents a structural shift in the relationship between crime and its sociological determinants. Specifically, that the magnitude and significance of these relationships differ between the pre-pandemic and post-pandemic periods across Minnesota counties. From Jake Boman and Owen Gallupe, this study further hypothesizes that post-pandemic crime patterns, particularly violent crime, are more strongly associated with indicators of family structure and demographic composition, such as the proportion of young males and family disruption, reflecting shifts in routine activities and social proximity during periods of social restriction<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Acknowledging the limitations of crime data highlighted by Nathan James and Wayne Logan as well as acknowledged in Norman and Arwood’s study, this study hypothesizes that observed changes in crime rates will vary across offense types and counties in ways that reflect not only true changes in criminal behavior but also differences in reporting practices and data quality. As a result, changes in the modeled relationships between crime and its determinants should be interpreted as the combination of social disruption and institutional variation rather than as being due to criminal activity alone.<br>
</p>
</section>
<section id="data-description" class="level3">
<h3 class="anchored" data-anchor-id="data-description">Data Description</h3>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The data being used in this study consists of two main parts, FBI crime and officer reports, as well as U.S Census Bureau county level ACS 5 year estimates. A collection of other sources were used to supplement and summarize these main sources as well. All of the data and code for this project is publicly available in this <a href="https://github.com/lborerseabloom/Econometrics.git">Github repository</a> to document the process of this research. Any graphs, tables, and results discussed in this paper can be replicated by following the steps detailed in the repository.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; To start, the FBI’s counts of crimes and officers were scraped from their website at a monthly level across all police agencies in Minnesota. As discussed in the literature review, James, Nathan, and Logan Rishard [2] highlight the intricacies to be aware of when using it to draw real world conclusions. Next, using the data from the National Law Enforcement Telecommunication Systems Originating Agency Identifier (NLETS ORI) directory [4] the local police agency data was mapped onto counties. As this data is a scanned PDF document Optical Character Recognition (OCR) was used to convert the data into machine readable text. This process does have some flaws due to the poor quality of the scan and a best effort was made to correct the minimal problems introduced into the data through this process. Additionally, as can be seen in the NLETS ORI directory some police agencies that operate federally or across the whole state cannot be tracked by county and are therefore left out of the crime counts.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="main_econometrics_files/figure-html/homicides_time_series-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Above, a brief look at the monthly/yearly plot of homicides over time shows the issues in the data which are present across all of the FBI’s monthly crime data. The most obvious of these are the December peaks as many police departments report the whole year of crime in December. This lasted from 1998 to 2013 when the FBI again changed how it receives and collects records. James and Logan’s 2008 report [2] details many of the previous shifts in crime data collection and reporting as well. However, grouping the crime data into years removes the month to month reporting problems. It will allow for more direct comparison to the Census estimates.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Alcohol sales tax information was retrieved from the Minnesota Department of Revenue’s website. While this data is lacking some documentation, a general overview of collection and reporting is available at the Minnesota Department of Revenue’s website [6]. The two main inaccuracies cited are that as the gross sales data is not used in calculating taxes it is under less scrutiny than other data and accuracy cannot be guaranteed, and that there are potential errors in location reporting for business with more than one location. For the first issue, this study is using the taxes collected on liquor sales which are closely examined for accuracy, additionally while any incorrect location reporting could affect the results directly it is stated to be only a negligible number of businesses.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Using the liquor gross receipts tax (at 2.5%) information provided from the years 2015-2019 a pre COVID 5 year average was obtained. The Minnesota Department of Revenue’s data for 2024, however, had not yet been released so a value for 2024 was obtained by averaging the slopes between the 2010-2019 and 2022-2023 years of unadjusted dollars where the trend appears fairly continuous and then adding this to the 2023 value. This approach is more appropriate than other methods of imputation given the clear and continuous trend in the data and another more standard method would be heavily impacted by the COVID outliers as can be seen below.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="main_econometrics_files/figure-html/alc_trends-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; With this data now organized and graphed above, the clear positive trend in the revenue from alcohol sales taxes can now be seen up until COVID. This then dips sharply during COVID and sees a clear structural shift afterwards. These trends , at least after COVID, follow the common narrative seen in studies such as the 2024 National Survey on Drug Use and Health [8] and the Minnesota Department of Health [9]. These reports suggest that alcohol use by adults and minors has decreased or stayed the same in the past years and had a slight uptick during COVID. The drop in sales during COVID could however represent a problem with taxes as a proxy as all in-person stores saw declines in consumerism during the pandemic.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; County level 5 year estimates (ACS5) for the demographic variables of interest during the years of 2015-2019 and 2020-2024 were then obtained from the U.S Census Bureau through the tidycensus package. These estimates have their own problems such as sampling and response bias [5]. The main problems from this census data are the fact that data on every county is only available in 5 year average estimates and that these numbers are estimates based on a sample of the population. However, the 5 year averaging is not a problem in our case as we want to examine structural changes resulting from the COVID-19 pandemic and an average across 5 years will be able to represent that. The sampling and response biases, generated from who is sampled and who chooses to respond to a poll, will have to be addressed in the final interpretation of the results as a potential source of bias.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The dependent variable of interest, crime rate, is calculated by summing a 5 year average of all part 1 index crimes collected from the FBI and dividing it by the total population estimate from the census. The available demographic variables (officers per 1000 people, median household income, the percent of households with less than $5000 income, the percent of people with a high school or greater degree, the percent of children missing parents, the percent non white, the percent young males, persons per household, persons per m<sup>2</sup>, and per capita net migration) used in Norman and Arwood’s 1998 study [1] were then calculated using a variety of census estimates.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The final data being used for modeling contains two rows for each of the 87 Minnesota counties representing the pre and post COVID periods with 5 year average estimates for 2015-2019 and 2020-2024 respectively. The variables used in Norman and Arwood’s 1998 study [1] will be tested in their effects on crime rates before and after to address the question of: how have the relationships between crime and its determinants changed over time, particularly in response to the COVID-19 pandemic?<br>
</p>
</section>
<section id="research-findings" class="level3">
<h3 class="anchored" data-anchor-id="research-findings">Research Findings</h3>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Using this data, a few graphical representations of crime rates can help to better understand the nature of the data before modeling.<br>
</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="main_econometrics_files/figure-html/homicides_time_series2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Using ACS 1 year estimates of population, a yearly plot of crime rates and population reveals a consistent downward trend in crime rates per capita, dropping with a steeper slope than the increase in population. This pattern suggests that crime rates have been declining naturally over time. However, consistent with the predictions in the study by Boman, J.H., Gallupe, O, [3] there is a local peak of crime in 2020 and 2021 during the pandemic lockdown. Interestingly, even before the pandemic there was still a sharp uptick in crime rates in 2019 suggesting other factors at play as well. Following this deviation, crime rates decline again by 2023, resuming the pre-pandemic trend. This indicates that the pandemic period represents a temporary disturbance rather than a lasting structural shift in Minnesotan crime trends.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="main_econometrics_files/figure-html/homicides_time_series3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Looking at the general distribution of crime rates post COVID we see a approximately normal distribution after a square root transformation, this transformation will be used through the rest of the modeling process. However the pre COVID distribution remains slightly left skewed but not dramatically. The right tails of both pre and post COVID distributions hold the largest counties suggesting there could be a relationship between population density and crime rates. The shape does not meaningfully change post COVID but there is a clear drop in crime rates able to be seen. This plot demonstrates again the dropping crime rates post COVID as well as a potential relationship between population density and crime.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="main_econometrics_files/figure-html/crime_and_pop_mapping-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; A spatial analysis of the post COVID five-year averages for crime rates and population reveals distinct geographic patterns and highlights the relationship between population and large cites with crime. Higher crime rates are concentrated within major urban centers, with a noticeable decline in surrounding suburban areas. Outside of the Twin Cities region, other population hubs also exhibit above-average crime rates. One clear outlier is Beltrami County, which can be seen as a clear yellow county in the upper central portion of the crime rate map despite its lack of a high population.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped caption-top table-sm small" data-quarto-postprocess="true">
<caption>Values and signifigance of changes in variables of interest</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">variable</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">mean_pre</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">mean_post</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">sd_pre</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">sd_post</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">median_household_income_acs5</td>
<td style="text-align: left;">61656.48276</td>
<td style="text-align: left;">77500.64368</td>
<td style="text-align: left;">11425.78664</td>
<td style="text-align: left;">12977.17976</td>
<td style="text-align: left;">0.00000</td>
</tr>
<tr class="even">
<td style="text-align: left;">pct_non_white</td>
<td style="text-align: left;">9.01708</td>
<td style="text-align: left;">13.85626</td>
<td style="text-align: left;">7.57129</td>
<td style="text-align: left;">8.71725</td>
<td style="text-align: left;">0.00013</td>
</tr>
<tr class="odd">
<td style="text-align: left;">pct_highschool_or_greater</td>
<td style="text-align: left;">91.37000</td>
<td style="text-align: left;">92.51558</td>
<td style="text-align: left;">2.75060</td>
<td style="text-align: left;">2.38527</td>
<td style="text-align: left;">0.00380</td>
</tr>
<tr class="even">
<td style="text-align: left;">crime_rate</td>
<td style="text-align: left;">0.01367</td>
<td style="text-align: left;">0.01055</td>
<td style="text-align: left;">0.00808</td>
<td style="text-align: left;">0.00736</td>
<td style="text-align: left;">0.00860</td>
</tr>
<tr class="odd">
<td style="text-align: left;">pct_lessthan_5kincome</td>
<td style="text-align: left;">4.54495</td>
<td style="text-align: left;">4.08114</td>
<td style="text-align: left;">1.30145</td>
<td style="text-align: left;">1.15803</td>
<td style="text-align: left;">0.01399</td>
</tr>
<tr class="even">
<td style="text-align: left;">per_capita_migration</td>
<td style="text-align: left;">0.06175</td>
<td style="text-align: left;">0.05681</td>
<td style="text-align: left;">0.01718</td>
<td style="text-align: left;">0.01665</td>
<td style="text-align: left;">0.05592</td>
</tr>
<tr class="odd">
<td style="text-align: left;">pct_young_males</td>
<td style="text-align: left;">3.20551</td>
<td style="text-align: left;">3.36270</td>
<td style="text-align: left;">0.58305</td>
<td style="text-align: left;">0.58480</td>
<td style="text-align: left;">0.07759</td>
</tr>
<tr class="even">
<td style="text-align: left;">pct_children_missing_parents</td>
<td style="text-align: left;">32.89281</td>
<td style="text-align: left;">32.57961</td>
<td style="text-align: left;">2.06612</td>
<td style="text-align: left;">2.63064</td>
<td style="text-align: left;">0.38376</td>
</tr>
<tr class="odd">
<td style="text-align: left;">officers</td>
<td style="text-align: left;">2.79728</td>
<td style="text-align: left;">2.71555</td>
<td style="text-align: left;">1.11009</td>
<td style="text-align: left;">0.65202</td>
<td style="text-align: left;">0.55471</td>
</tr>
<tr class="even">
<td style="text-align: left;">persons_per_household</td>
<td style="text-align: left;">2.45877</td>
<td style="text-align: left;">2.45170</td>
<td style="text-align: left;">0.20076</td>
<td style="text-align: left;">0.16975</td>
<td style="text-align: left;">0.80233</td>
</tr>
<tr class="odd">
<td style="text-align: left;">per_capita_alc_taxes</td>
<td style="text-align: left;">16.41118</td>
<td style="text-align: left;">16.32717</td>
<td style="text-align: left;">7.45967</td>
<td style="text-align: left;">7.28797</td>
<td style="text-align: left;">0.94019</td>
</tr>
<tr class="even">
<td style="text-align: left;">persons_per_m2</td>
<td style="text-align: left;">0.00005</td>
<td style="text-align: left;">0.00005</td>
<td style="text-align: left;">0.00016</td>
<td style="text-align: left;">0.00016</td>
<td style="text-align: left;">0.95437</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; An examination of the predictive variables used in [1] indicate no statistically significant changes at the 5% level between the pre and post-COVID periods for the per capita migration, percent young males, percent of children missing parents, officers per 1,000 residents, persons per household, per capita alcohol taxes, and persons per square meter. However, across the rest of the variables we see relatively larger and more significant changes particularly across crime rates, income, education, heterogeneity, and revenue from alcohol taxes.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped caption-top table-sm small" data-quarto-postprocess="true">
<caption>Signifigance of correlation with crime rates</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">variable</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">persons_per_m2</td>
<td style="text-align: right;">0.4988668</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">per_capita_migration</td>
<td style="text-align: right;">0.4249200</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">pct_non_white</td>
<td style="text-align: right;">0.4094770</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">per_capita_alc_taxes</td>
<td style="text-align: right;">0.3032593</td>
<td style="text-align: right;">0.0000475</td>
</tr>
<tr class="odd">
<td style="text-align: left;">persons_per_household</td>
<td style="text-align: right;">0.2517364</td>
<td style="text-align: right;">0.0008057</td>
</tr>
<tr class="even">
<td style="text-align: left;">pct_highschool_or_greater</td>
<td style="text-align: right;">-0.1907060</td>
<td style="text-align: right;">0.0117145</td>
</tr>
<tr class="odd">
<td style="text-align: left;">pct_young_males</td>
<td style="text-align: right;">0.1832375</td>
<td style="text-align: right;">0.0155131</td>
</tr>
<tr class="even">
<td style="text-align: left;">pct_lessthan_5kincome</td>
<td style="text-align: right;">0.1380964</td>
<td style="text-align: right;">0.0691860</td>
</tr>
<tr class="odd">
<td style="text-align: left;">officers</td>
<td style="text-align: right;">0.1084093</td>
<td style="text-align: right;">0.1544724</td>
</tr>
<tr class="even">
<td style="text-align: left;">pct_children_missing_parents</td>
<td style="text-align: right;">0.0864215</td>
<td style="text-align: right;">0.2568433</td>
</tr>
<tr class="odd">
<td style="text-align: left;">median_household_income_acs5</td>
<td style="text-align: right;">-0.0067137</td>
<td style="text-align: right;">0.9299388</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Further, correlation analyses show that many of the variables of interest exhibit reasonably strong and significant correlations with per capita crime. Some of the largest differences seen here between this study and Norman and Arwood’s [1] is the finding of persons per household to be significant while they found no significant correlation, as well as the insignificance of the correlations with median household income and officers per 1000 people. Particularly the persons per household correlation change aligns with Boman and Gallupe’s 2020 study suggesting that the more people quarantined together, the more violence that could occur.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="main_econometrics_files/figure-html/relationship_analysis-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; After fitting preliminary models, pct_children_missing_parents, pct_young_males, and persons_per_household were removed due to consistently high p-values (greater than 0.50) across model specifications. The variable pct_lessthan_5kincome was also removed from the main regression models because of its strong negative correlation (−0.70) with median household income and because it represents a fixed dollar amount whose real value changes over time, making it an unstable measure in time series context. Variables prefixed with log_ were transformed using the natural logarithm to stabilize variance and reduce the influence of extreme values often produced from the twin cities counties (Ramsey and Hennipen).<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Three additional features were also introduced to capture structural differences across counties: an indicator for whether a county contains a federally recognized reservation (reservations), an indicator for counties containing one of Minnesota’s five largest cities (top_cities; Ramsey, Hennepin, Olmsted, St.&nbsp;Louis, and Stearns), and a pre-/post-COVID indicator distinguishing observations from the 2019 (pre) and 2024 (post) ACS 5-year estimates. Together, these steps yielded a set of nine primary predictors used to explain variation in per-capita crime rates.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Across these predictors in the above plot, a potentially significant change in slope can be seen for log_officers, log_per_capita_alc_taxes, pct_highschool_or_greater, per_capita_migration, and the reservation and top cities indicator variables. Due to the plots above, their interactions with the pre and post COVID indicator will also be tested in subsequent regression models.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; To further assess the validity of these variable selection decisions and to identify any potentially omitted predictors or interaction effects, a LASSO regression was fit using the full set of available variables and all interaction terms. This model provides an additional perspective on the relative importance of the full set of potential explanatory variables. Unlike other traditional regressions, which rely on statistical significance conditional on a specified model, the LASSO model penalizes coefficient size and shrinks less informative variables exactly to zero. As a result, variables that remain in the model and have estimated coefficients can be interpreted as those with the strongest predictive relationships with crime rates in a high-dimensional setting. Additionally as the LASSO model relies on normalized predictor values all of the magnitudes of the coefficients can be directly compared and interpreted as variable importance. These factors make it a useful tool in variable selection, as all unimportant variables will have their coefficients set to 0 or near 0 and dropped automatically.<br>
</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped caption-top table-sm small" data-quarto-postprocess="true">
<caption>LASSO Regression Summary</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">s0</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">reservations:per_capita_migration</td>
<td style="text-align: right;">0.4735882</td>
</tr>
<tr class="even">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">0.3417738</td>
</tr>
<tr class="odd">
<td style="text-align: left;">post_covid:per_capita_migration</td>
<td style="text-align: right;">0.0222235</td>
</tr>
<tr class="even">
<td style="text-align: left;">log_persons_per_m2</td>
<td style="text-align: right;">0.0113038</td>
</tr>
<tr class="odd">
<td style="text-align: left;">log_per_capita_alc_taxes:per_capita_migration</td>
<td style="text-align: right;">0.0056033</td>
</tr>
<tr class="even">
<td style="text-align: left;">officers:pct_young_males</td>
<td style="text-align: right;">0.0015277</td>
</tr>
<tr class="odd">
<td style="text-align: left;">pct_lessthan_5kincome:log_persons_per_m2</td>
<td style="text-align: right;">0.0005672</td>
</tr>
<tr class="even">
<td style="text-align: left;">persons_per_household:log_persons_per_m2</td>
<td style="text-align: right;">0.0005175</td>
</tr>
<tr class="odd">
<td style="text-align: left;">pct_young_males:log_persons_per_m2</td>
<td style="text-align: right;">0.0003083</td>
</tr>
<tr class="even">
<td style="text-align: left;">per_capita_alc_taxes:pct_lessthan_5kincome</td>
<td style="text-align: right;">0.0002772</td>
</tr>
<tr class="odd">
<td style="text-align: left;">officers:log_officers</td>
<td style="text-align: right;">0.0001589</td>
</tr>
<tr class="even">
<td style="text-align: left;">pct_children_missing_parents:log_pct_non_white</td>
<td style="text-align: right;">0.0001438</td>
</tr>
<tr class="odd">
<td style="text-align: left;">pct_children_missing_parents:reservations</td>
<td style="text-align: right;">0.0001105</td>
</tr>
<tr class="even">
<td style="text-align: left;">per_capita_alc_taxes:log_officers</td>
<td style="text-align: right;">-0.0004148</td>
</tr>
<tr class="odd">
<td style="text-align: left;">post_covid:reservations</td>
<td style="text-align: right;">-0.0017824</td>
</tr>
<tr class="even">
<td style="text-align: left;">officers:persons_per_m2</td>
<td style="text-align: right;">-2.2234808</td>
</tr>
<tr class="odd">
<td style="text-align: left;">persons_per_household:persons_per_m2</td>
<td style="text-align: right;">-4.4938320</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The LASSO results indicate that interactions involving population density, migration, alcohol taxation, and reservation status retain the largest non-zero coefficients. In particular, the interaction between reservations and per_capita_migration emerges as the most influential positive predictor, suggesting that migration is strongly associated with crime rates in counties containing reservations. Several additional interaction terms involving population density (persons_per_m2), household size, alcohol tax revenue, and policing levels also retain non-zero coefficients, demonstrating the potential importance of population density and economic factors in explaining crime variation.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; While some untransformed demographic and household structure variables that were excluded from the primary regression models reappear in the LASSO results through interaction terms, their coefficients are comparatively small, indicating limited incremental predictive value once dominant spatial and economic factors are accounted for. Overall, the LASSO model supports the primary modeling strategy by confirming that population density, migration, alcohol-related revenue, reservation status, and urban density contain the most information for explaining county-level crime, while many alternative demographic measures contribute little additional explanatory power in a high-dimensional setting.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="main_econometrics_files/figure-html/persons_per_household_persons_per_m2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Potential interaction effects were then examined above using interaction plots constructed by grouping continuous moderators with approximately equal numbers of observations using the cut_number() function in ggplot2. This approach allows for the inspection of shifts in slope while maintaining sufficient observations within each group to avoid over weighting any of the sections.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Inspection of the interaction between persons per square meter (persons_per_m2), and persons per household (persons_per_household) initially suggested shifts in slopes across household-size groups. However, closer examination revealed that this apparent interaction was driven largely by non-linearity in the untransformed population density measure. In particular, the lowest persons-per-household group exhibited a sharply different pattern that becomes much less pronounced after a logarithmic transformation. This provides strong evidence that the significance of the interaction in the unlogged specification was spurious and arose from misspecification rather than a meaningful relationship. A similar pattern was observed for the interaction between officers per 1000 people and the unlogged population density, where a large estimated interaction coefficient coincided with clear violations of linearity. Due to this both of these interactions do not appear in the model as they seem to largely rely on spurious correlation and lose significance once transformed.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; As can be seen below, the interaction between reservation status and per-capita net migration remained stable across specifications and did not exhibit the same modeling problems. The relationship between migration and crime is approximately linear within both reservation and non-reservation counties, and no transformation was required to achieve linearity or variance stabilization. This interaction also has a comparatively large coefficient in the LASSO model, supporting its relevance. As a result, the reservation-migration interaction term was retained in the final model as a substantively meaningful effect.<br>
</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="main_econometrics_files/figure-html/reservations-per_capita_migration-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; While migration may plausibly proxy for population turnover or density-related processes, including additional interaction terms between migration and population density (persons_per_m2), racial composition (pct_non_white), median household income, and alcohol tax revenue does not change the estimated reservation–migration interaction. In those models, the migration interaction with other terms remains statistically insignificant, while the reservation interaction retains both its magnitude and statistical significance.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; This interaction implies that increases in net migration are associated with higher crime rates in counties containing reservations compared to counties without reservations. These different slopes suggest that migration operates through distinct mechanisms in reservation counties, potentially reflecting differences in housing availability, available jobs, or access to social services. While the analysis does not identify a causal mechanism, the significance of this interaction after controlling for other economic conditions, population density, racial composition, and alcohol-related revenue indicates that reservation status meaningfully moderates the relationship between migration and crime.<br>
</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped caption-top table-sm small" data-quarto-postprocess="true">
<caption>Regression Models with Classical and Robust Standard Errors Against the Square Root of Crime Rates</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error_normal</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error_robust</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">0.3460412</td>
<td style="text-align: right;">0.031</td>
<td style="text-align: right;">0.046</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">median_household_income_acs5</td>
<td style="text-align: right;">-0.0000013</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">log_persons_per_m2</td>
<td style="text-align: right;">0.0204319</td>
<td style="text-align: right;">0.002</td>
<td style="text-align: right;">0.002</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">reservations:per_capita_migration</td>
<td style="text-align: right;">1.2950588</td>
<td style="text-align: right;">0.251</td>
<td style="text-align: right;">0.274</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">reservations</td>
<td style="text-align: right;">-0.0571894</td>
<td style="text-align: right;">0.015</td>
<td style="text-align: right;">0.017</td>
<td style="text-align: right;">0.001</td>
</tr>
<tr class="even">
<td style="text-align: left;">log_pct_non_white</td>
<td style="text-align: right;">0.0089669</td>
<td style="text-align: right;">0.003</td>
<td style="text-align: right;">0.003</td>
<td style="text-align: right;">0.005</td>
</tr>
<tr class="odd">
<td style="text-align: left;">log_per_capita_alc_taxes</td>
<td style="text-align: right;">0.0197153</td>
<td style="text-align: right;">0.005</td>
<td style="text-align: right;">0.008</td>
<td style="text-align: right;">0.012</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The above regression results reveal several robust relationships between county-level crime rates and key socioeconomic and spatial predictors. Median household income is negatively associated with crime, consistent with prior literature, while population density (measured as the log of persons per square meter), per-capita alcohol tax revenue, and the proportion of non-white residents are all positively associated with higher crime rates. Counties containing reservations exhibit significantly lower baseline crime rates on average; however, this effect is strongly moderated by net migration, as reflected in the large and highly significant interaction between reservation status and per-capita migration.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; A large concern with county-level ACS data is the presence of both spatial and temporal autocorrelation, which can lead to downward-biased standard errors and overly generous p-values under OLS assumptions. To address this issue, the model is estimated using standard errors that are robust to clustering. Both classical and clustering-robust (CR2) standard errors are reported for comparison, inference is also based on these cluster-robust estimators. Multiple clustering and heteroskedastic corrections were tried, including CR1 (Liang–Zeger), CR2, and HC. Across all three approaches, the key coefficients, particularly the reservation-by-migration interaction, remain statistically significant. As stated by Alberto Abadie et al.&nbsp;[10], clustering errors largely are overly conservative, however CR2 standard errors are still reported here, as in this case they don’t impact significance of the chosen predictors heavily and provide reasonable increases in standard errors while avoiding the excessive corrections of CR3.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Several variables and interaction terms examined in earlier specifications, including policing levels, urban-county indicators, educational attainment, and all COVID interactions were excluded from the final model due to consistent insignificance once robust inference was applied. Notably, the post-COVID indicator itself does not significantly alter the relationships between crime and its predictors, suggesting that while crime rates increased during the pandemic period, the structural relationships between crime and traditional sociological factors remained largely the same.<br>
</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">R2</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Adj_R2</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">RMSE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.662</td>
<td style="text-align: right;">0.65</td>
<td style="text-align: right;">0.021</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; This model explains approximately 66.2% of the variation in county-level crime rates and achieves a root mean squared error (RMSE) that is roughly half the standard deviation of observed crime rates, indicating a strong overall fit. Also, the adjusted R<sup>2</sup> remains close to the unadjusted R<sup>2</sup>, suggesting that the model is not overfitting and that the included predictors contribute meaningfully to explaining variation in crime rates.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; As seen below, the residuals are approximately centered at 0 with no obvious outliers or patterns further demonstrating the validity of an OLS approach to this data.<br>
</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="main_econometrics_files/figure-html/acs5_modeling_resids_v_fits-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Additionally, the model also largely satisfies it’s normality in the residuals assumption with the majority of residuals matching up with the normal distribution as can be seen below. However on both upper and lower tails there is some drift above and below the theoretical normal distribution which is contained to only 6 points and not enough to not impact the conclusions from this model meaningfully.<br>
</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="main_econometrics_files/figure-html/acs5_modeling_resid_normality-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The linear model reveals a limited set of robust predictors of county-level crime, with many traditional sociological variables losing explanatory power once controls and interaction terms are included. As in Norman and Arwood’s previous work, only a small subset of variables remain statistically significant at conventional levels, as well as all interaction terms with the post-COVID indicator not being statistically distinguishable from zero.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The first notable finding concerns median household income, which exhibits a negative relationship with per-capita crime rates. The coefficient on median_household_income_acs5 (-0.0000013) implies that a $10,000 increase in median household income is associated with a reduction of approximately 0.169 crimes per 1,000 residents on average, holding all else constant. While modest, this effect is precisely estimated and highly significant, suggesting that higher-income counties consistently experience lower crime rates, controlling for density, demographics, and other covariates. This aligns with Norman and Arwood’s earlier findings that economic deprivation is associated with higher crime, supporting the conclusion that economic conditions remain a meaningful determinant.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Population density emerges as a stable predictor but modest in it’s effects on crime. The log of persons per square meter is positive and highly significant (0.0204319), implying for every additional 10% increase in population density you would expect an average increase of .0042 crimes per 1000 people holding all else constant. This finding strengthens the evidence relative to Norman and Arwood’s earlier work, where population density was only marginally significant, and suggests that urban density is a key structural factor in crime.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The reservation indicator and its interaction with per-capita net migration are both highly significant. Counties with a reservation have slightly lower baseline crime rates (−0.057) on the square root scale), but the reservation-migration interaction is substantially large (1.29). This implies that a for every additional migration per 1000 people into a reservation county is associated with roughly 0.00129 additional violent crimes per resident, whereas migration has negligible impact in non-reservation counties. This interaction is robust to transformations, outlier removal, and cluster-robust inference, demonstrating that migration effects on crime are context-dependent and particularly pronounced in counties containing reservations.This stability suggests that the observed relationship reflects long-standing structural and institutional factors and not pandemic-related disruptions. Another potential reason for this can be seen in the FBI’s handling of crimes committed on tribal land [7]. The majority of crimes used in the operationalization of crime rates are included under the ‘serious’ offenses, which if committed on tribal land, are automatically handled by the FBI bypassing the potential source of under reporting from the police to the FBI.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The log of the percent of non-white residents is positive (0.009) but with only a very marginal effect; a 10% increase in the percent non-white population is associated with approximately 0.0008 additional crimes per 1,000 residents. This suggests that racial heterogeneity, while correlated with crime in simpler models, does not independently explain variation once density, income, and other controls are included. As in stated prior work, this relationship likely reflects broader geographic and socioeconomic clustering rather than a direct causal mechanism.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Similarly, per-capita alcohol tax revenue (log_per_capita_alc_taxes) is positive but modest (0.0197153): a 10% increase in per-capita alcohol tax revenue is associated with approximately 0.004 additional crimes per 1,000 residents. Educational attainment (percentage with a high school degree or greater) is not significant, suggesting that education primarily proxies for density and urbanization rather than exerting a direct effect on crime.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Variables capturing large city status, police presence, and migration alone are not significant after controls are included. Their estimated impacts in original units are close to zero, further highlighting that migration effects in non-reservation counties are minimal. The inclusion of the reservation × migration interaction explains most of the predictive variation previously attributed to migration, underscoring the importance of context-dependent relationships for these variables.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Finally, the post-COVID indicator itself is highly statistically insignificant and removed from the model, suggesting that once demographic and economic factors are accounted for, there is no clear evidence of a structural shift in the relationship between crime and its traditional predictors following the pandemic even if previous plots has shown some evidence of its effects. The insignificance of nearly all interaction terms reinforces this conclusion, indicating that COVID-19 did not structurally alter how socioeconomic characteristics relate to crime across counties. This interpretation is again supported by structural break tests below, which fail to detect meaningful parameter shifts over time at again highly insignificant levels.<br>
</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    M-fluctuation test

data:  total_model
f(efp) = 1.2684, p-value = 0.4426</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    OLS-based CUSUM test

data:  cumsum_process
S0 = 0.78581, p-value = 0.5674</code></pre>
</div>
</div>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; A model is now fit using the difference between pre and post COVID to see if any of the changes in explanatory variables are associated with a change in crime rates across COVID. Using this approach, the only variables found to have a statistically significant relationship at the &lt;.05 level on the change in crime rates is change in the population density measured in m<sup>2</sup> as well as the change in the proportion of young males in the population. The negative coefficient suggests that counties experiencing increases in population density over this period tended to see relative declines in crime rates, while counties with decreasing density experienced relative increases. The borderline significance of young males in this case seems to be a type 1 error, especially due to its high lack of significance in other models. No other changes in variables were found to be statistically significant predictors of changes in crime rates, indicating that much of the observed variation in crime across counties during this period is not explained by concurrent changes in these factors.<br>
</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped caption-top table-sm small" data-quarto-postprocess="true">
<caption>Regression Model for Differences in the Square Root of Crime Rate</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd" data-grouplength="3">
<td colspan="4" style="border-bottom: 1px solid"><strong>Difference Model</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">(Intercept)</td>
<td style="text-align: right;">-0.0103982</td>
<td style="text-align: right;">0.002</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">log_persons_per_m2_diff</td>
<td style="text-align: right;">-0.1390473</td>
<td style="text-align: right;">0.056</td>
<td style="text-align: right;">0.014</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">pct_young_males_diff</td>
<td style="text-align: right;">-0.0102769</td>
<td style="text-align: right;">0.005</td>
<td style="text-align: right;">0.045</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Examining the metrics of this differenced model as well as a LASSO regression model we see a similar story. The extremely low R<sup>2</sup> shows again that none of the considered factors are explaining much of the actual variance in changes of crime rates before and after COVID.<br>
</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">R2</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Adj_R2</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">RMSE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.105</td>
<td style="text-align: right;">0.084</td>
<td style="text-align: right;">0.015</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The differenced LASSO model also only selects the population density measure, proportion of young males, and percent non-white. The percent non-white variable remains relatively insignificant (p=.185) in the OLS regression. The two other variables are estimated again with a negative coefficients showing them as the only potentially meaningful predictors among these traditional sociological factors for explaining the changes in crime rates over COVID. Again the coefficient for young males remains much lower than for population density further showcasing its potential invalidity as a predictor of crime.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped caption-top table-sm small" data-quarto-postprocess="true">
<caption>LASSO Regression Summary</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">s0</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">log_pct_non_white_diff</td>
<td style="text-align: right;">0.0027588</td>
</tr>
<tr class="even">
<td style="text-align: left;">pct_young_males_diff</td>
<td style="text-align: right;">-0.0045553</td>
</tr>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-0.0147097</td>
</tr>
<tr class="even">
<td style="text-align: left;">log_persons_per_m2_diff</td>
<td style="text-align: right;">-0.0734665</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="conclusions" class="level3">
<h3 class="anchored" data-anchor-id="conclusions">Conclusions</h3>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; This study has revisited and extended the county-level framework of Norman and Arwood to ask whether COVID changed the relationships between county sociological characteristics and part I crime in Minnesota. This study has been done using five-year ACS averages (2015–2019 vs.&nbsp;2020–2024) and aggregated crime counts from the FBI. From this data some key takeaways have become clear.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Firstly, median household income is robustly and negatively associated with county crime rates: wealthier counties have lower crime, holding other controls constant. Population density is also a stable, positive predictor of higher crime. These results stem from OLS regression with robust standard errors, as well as LASSO penalization and together account for a large proportion of cross-county variations in crime rates.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Secondly, the reservation-per-capita migration interaction emerges as a highly significant and substantively meaningful predictor. While migration alone does not systematically affect crime across all counties, increases in net migration are associated with disproportionately higher crime in counties containing reservations, even after controlling for income, density, racial composition, and alcohol-tax revenue. This interaction is robust across specifications and transformations, highlighting a context-dependent pathway for crime variation that was not captured in earlier studies due to the lack of a reservation indicator variable.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Thirdly, the post-COVID indicator and its interaction terms remain statistically insignificant, and structural-break tests detect no meaningful changes in parameter relationships across the two periods. Although crime rates fluctuated during the pandemic, these fluctuations are not explained by changes in the main sociological predictors, indicating resilience in the structural determinants of county-level crime.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Fourthly, other variables such as education, racial composition, per-capita police officers, migration alone, and alcohol-tax revenue show only weak or conditional effects once income, density, urban indicators, and reservation status are included. The LASSO model reinforces this conclusion, retaining a small subset of variables (density, migration, alcohol revenue, racial composition, reservation and urban indicators, and income) as carrying most of the predictive information. In models of differenced crime rates (post minus pre), almost none of the observed changes in these sociological variables explain the variation, with population density change as the lone consistent and reliable predictor—but with a small negative coefficient, suggesting that counties experiencing small density increases tended to see relative decreases in crime.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Overall, these findings suggest that economic standing, urban density, and the interaction between migration and reservation status are the most robust determinants of county-level crime in Minnesota. While the pandemic produced short-term fluctuations in crime, the structural relationships between crime and these key predictors remained largely stable. These results reinforce the importance of accounting for both contextual heterogeneity (such as reservations) and spatially correlated factors when modeling crime at the county level, while also highlighting the limitations of standard ACS variables for explaining short-term changes in crime.<br>
</p>
</section>
<section id="limitations-and-future-work" class="level3">
<h3 class="anchored" data-anchor-id="limitations-and-future-work">Limitations and Future Work</h3>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; These crime counts come from the Federal Bureau of Investigation (FBI) and inherit known reporting limitations (underreporting, changes in definitions and agency reporting practices, variation across local agencies). For one, jurisdictional and tribal-land reporting differences can affect counts for reservation counties (the FBI’s handling of serious offenses on tribal lands differs from municipal reporting), which complicates direct comparison across counties.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Furthermore, many of the sociological predictors are five-year ACS averages reported by the U.S. Census Bureau (due to it being the most granular level at which every Minnesota county is reported); these smooth short-term dynamics and carry sampling/response errors as well as being estimates rather than true values.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; For future work I recommend a variety of continuations namely: spatial econometric approaches that explicitly model correlations between neighboring counties and use yearly (not five-year averaged) data where available; analyses at finer geographic units as crime is not ever happening on county levels; incorporation of new indicators (housing instability, unemployment, and mobility among others) as well as administrative data about police reporting practices; and (d) careful treatment of tribal jurisdiction issues to better understand the reservation result.<br>
</p>
</section>
<section id="final-summary" class="level3">
<h3 class="anchored" data-anchor-id="final-summary">Final Summary</h3>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Overall, the pandemic produced a noticeable, short-lived rise in some serious offenses, but it did not fundamentally reshape the cross-county relationships between serious crime and a county’s socioeconomic and spatial characteristics. Income inequality and urban density remain the dominant, stable predictors of county level crime in Minnesota; and many of the commonly discussed sociological measures explain little additional cross-county variation once these structural factors are accounted for.<br>
</p>
<div style="text-align: center;">
<p><strong>Citations</strong></p>
<p>[1] Norman, J. Mark &amp; Arwood, Donald E. (1998). <em>A Social Disorganization Theory of County Crime Rates in Minnesota</em>. <em>Great Plains Sociologist</em>, 11(2), Article 2.<br>
<a href="https://openprairie.sdstate.edu/greatplainssociologist/vol11/iss2/2" class="uri">https://openprairie.sdstate.edu/greatplainssociologist/vol11/iss2/2</a></p>
<p>[2] James, Nathan &amp; Logan, Rishard. (2008). <em>How Crime in the United States Is Measured</em>. Congressional Research Service, Library of Congress.<br>
<a href="https://apps.dtic.mil/sti/html/tr/ADA476144/" class="uri">https://apps.dtic.mil/sti/html/tr/ADA476144/</a></p>
<p>[3] Boman, J. H., &amp; Gallupe, O. (2020). <em>Has COVID-19 Changed Crime? Crime Rates in the United States during the Pandemic</em>. <em>American Journal of Criminal Justice</em>, 45, 537–545.<br>
<a href="https://doi.org/10.1007/s12103-020-09551-3" class="uri">https://doi.org/10.1007/s12103-020-09551-3</a></p>
<p>[4] National Law Enforcement Telecommunications System (NLETS). (1981). <em>ORI (Originating Agency Identifier) Directory</em>. U.S. Department of Justice. Grant No.&nbsp;75-SS-99-6018.<br>
</p>
<p>[5] U.S. Census Bureau. (2025, August 19). <em>Comparing ACS Data</em>.<br>
<a href="https://www.census.gov/programs-surveys/acs/guidance/comparing-acs-data.html" class="uri">https://www.census.gov/programs-surveys/acs/guidance/comparing-acs-data.html</a></p>
<p>[6] Minnesota Department of Revenue. <em>Sales and Use Tax Statistics for Liquor Sales and 2.5% Tax by County.</em><br>
<a href="https://www.revenue.state.mn.us/sales-and-use-tax-statistics-and-annual-reports" class="uri">https://www.revenue.state.mn.us/sales-and-use-tax-statistics-and-annual-reports</a></p>
<p>[7] Federal Bureau of Investigation. <em>Law Enforcement on Tribal Land.</em><br>
<a href="https://www.fbi.gov/investigate/violent-crime/indian-country-crime" class="uri">https://www.fbi.gov/investigate/violent-crime/indian-country-crime</a></p>
<p>[8] Substance Abuse and Mental Health Services Administration. (2025). <em>Key substance use and mental health indicators in the United States: Results from the 2024 National Survey on Drug Use and Health</em> (HHS Publication No.&nbsp;PEP25-07-007; NSDUH Series H-60). Center for Behavioral Health Statistics and Quality.<br>
<a href="https://www.samhsa.gov/data/sites/default/files/reports/rpt56287/2024-nsduh-annual-national-report.pdf" class="uri">https://www.samhsa.gov/data/sites/default/files/reports/rpt56287/2024-nsduh-annual-national-report.pdf</a></p>
<p>[9] Minnesota Department of Health. <em>Alcohol Use Among Youth in Minnesota.</em><br>
<a href="https://www.health.state.mn.us/communities/alcohol/documents/youthalcoholuse.pdf" class="uri">https://www.health.state.mn.us/communities/alcohol/documents/youthalcoholuse.pdf</a></p>
<p>[10] Abadie, A., Athey, S., Imbens, G. W., &amp; Wooldridge, J. (2017). <em>When should you adjust standard errors for clustering?</em> National Bureau of Economic Research Working Paper No.&nbsp;24003.<br>
<a href="https://www.nber.org/system/files/working_papers/w24003/w24003.pdf" class="uri">https://www.nber.org/system/files/working_papers/w24003/w24003.pdf</a></p>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>